### ISSUE TITLE
Help using .Net Core 8

### ISSUE THREAD

**Issue by ronlhayes** [PaulHatch/vault-data-protection#2]
Thanks for creating this - exactly what I was looking for, We are moving from Azure to GCP so no longer able to use AKV. I configured using an existing secret path and assume that new secrets would be created using names similar to what is used for other PersistKeys* methods. I am running locally using the Vault container (dev) and have confirmed I can create new secrets. Anyway, all looks good until I hit the first _protector.Protect() method and I get the following exception:

fail: Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingProvider[48]
      An error occurred while reading the key ring.
      System.MissingMethodException: Method not found: 'System.Collections.Generic.Dictionary`2<System.String,System.Object> VaultSharp.V1.Commons.SecretData.get_Data()'.
         at VaultSharpDataProtection.VaultSharpXmlRepository.GetAllElements()
         at Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager.GetAllKeys()
         at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingProvider.CreateCacheableKeyRingCore(DateTimeOffset now, IKey keyJustAdded)
         at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingProvider.Microsoft.AspNetCore.DataProtection.KeyManagement.Internal.ICacheableKeyRingProvider.GetCacheableKeyRing(DateTimeOffset now)
         at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingProvider.GetCurrentKeyRingCore(DateTime utcNow, Boolean forceRefresh)
info: Microsoft.AspNetCore.DataProtection.Internal.DataProtectionHostedService[0]
      Key ring failed to load during application startup.
      System.MissingMethodException: Method not found: 'System.Collections.Generic.Dictionary`2<System.String,System.Object> VaultSharp.V1.Commons.SecretData.get_Data()'.
         at VaultSharpDataProtection.VaultSharpXmlRepository.GetAllElements()
         at Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager.GetAllKeys()
         at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingProvider.CreateCacheableKeyRingCore(DateTimeOffset now, IKey keyJustAdded)
         at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingProvider.Microsoft.AspNetCore.DataProtection.KeyManagement.Internal.ICacheableKeyRingProvider.GetCacheableKeyRing(DateTimeOffset now)
         at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingProvider.GetCurrentKeyRingCore(DateTime utcNow, Boolean forceRefresh)
         at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingProvider.GetCurrentKeyRing()
         at Microsoft.AspNetCore.DataProtection.Internal.DataProtectionHostedService.StartAsync(CancellationToken token)

Is it possible .Net Core 8 has made some breaking changes? Any help would be greatly appreciated.

-Ron

**Comment by PaulHatch** [comment]
Possible, I will try to have a look later today.

**Comment by PaulHatch** [comment]
This was already upgrade to 8 some time ago, closing.
